# pre-commit configuration file
# Ref: https://pre-commit.com/

default_language_version:
  python: python3.11

repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
        verbose: true
      - id: check-case-conflict
        verbose: true
      - id: check-executables-have-shebangs
        verbose: true
      - id: check-shebang-scripts-are-executable
        verbose: true
      - id: check-symlinks
        verbose: true
      - id: check-toml
        verbose: true
      - id: check-yaml
        verbose: true
      - id: end-of-file-fixer
        verbose: true
      - id: trailing-whitespace
        verbose: true


#  # Pylint
#  # https://pylint.readthedocs.io/en/latest/user_guide/installation/pre-commit-integration.html
#  - repo: local
#    hooks:
#      - id: pylint
#        name: pylint
#        entry: pylint
#        language: system
#        types: [ python ]
#        args: [ "--rcfile=pyproject.toml" ]
#
#  # mypy
#  - repo: https://github.com/pre-commit/mirrors-mypy
#    rev: 'v1.4.1'
#    hooks:
#      - id: mypy
#        args: ['--strict', '--ignore-missing-imports', '--config-file pyproject.toml']

  # isort - format imports
  # https://pycqa.github.io/isort/docs/configuration/pre-commit.html
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: ["--settings-path", "pyproject.toml"]
        verbose: true


  # Black - code formatter
  # https://black.readthedocs.io/en/stable/integrations/source_version_control.html
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black-jupyter
        args: ["--color", "--config", "pyproject.toml"]
        verbose: true


  # Conventional commits
  # https://github.com/compilerla/conventional-pre-commit
