name: full_env

channels:
  - conda-forge
  - defaults

dependencies:
  # Base
  - python
  - pip
  # Testing
  - pytest
  - pytest-cov
  - codecov
  - pylint
  - black
  - pre-commit

#  - pip:
#    - pip-only dependencies
