# Config file for the 'autolabeler' functionality of the GitHub action 'release-drafter',
# used in the workflow '.github/workflows/pr_labeler.yaml'

# References:
#  https://github.com/release-drafter/release-drafter#autolabeler


autolabeler:
  - label: breaking
    title:
      - '/^(build|chore|ci|docs|feat|fix|perf|refactor|release|revert|style|test)(\(.*\))?\!\: /'

  - label: build
    title:
      - '/^build/'

  - label: chore
    title:
      - '/^chore/'

  - label: ci
    title:
      - '/^ci/'

  - label: documentation
    title:
      - '/^docs/'

  - label: enhancement
    title:
      - '/^feat/'

  - label: fix
    title:
      - '/^fix/'

  - label: performance
    title:
      - '/^perf/'

  - label: refactor
    title:
      - '/^refactor/'

  - label: release
    title:
      - '/^release/'

  - label: revert
    title:
      - '/^revert/'

  - label: style
    title:
      - '/^style/'

  - label: test
    title:
      - '/^test/'
