

name: '🖥 App  🐞 Bug Report  📱 API'
description: >-
  Report a problem encountered while using the application, such as unexpected results and errors.

labels: ["Bug: App", "Status: Triage"]
assignees:
  - aariam

body:

  - type: markdown
    attributes:
      value: >-
        <p align="justify">
          Thank you for taking the time to report a problem in {metadata[project][name]};
          we greatly appreciate your contribution! ❤️🙏
        </p>
        <h2>Terms and Conditions</h2>
        <p align="justify">
          Before submitting a report, please take a moment to review and accept our terms and conditions;
          they will help us process the issue as fast as possible,
          and not bother you with additional questions.
        </p>
        <h3>⛔ Choosing the right form</h3>
        <ul>
          <li>
            <p align="justify">
              Please note that this form is specifically for reporting a
              <b>non-security-related bug</b>
              in the
              {metadata[project][name]}
              API, i.e. an unexpected behavior that occurs while using the application,
              either as an import package, a command-line tool, or via a GUI.
            </p>
          </li>
          <li>
            <p align="justify">
              To 🚨
              <a href="{metadata[urls][github][security][home]}"><b>report a security vulnerability</b></a>
              🚨 please first read our
              <a href="{metadata[urls][github][security][policy]}">security policy</a>,
              and fill a
              <a href="{metadata[urls][github][security][new_advisory]}">private security advisory form</a>
              instead.
            </p>
          </li>
          <li>
            <p align="justify">
              For other types of issues, such as problems in
              <a href="{metadata[urls][github][issues][new][app_bug_setup]}">setup</a>,
              <a href="{metadata[urls][github][issues][new][docs_bug_site]}">website</a>, or
              <a href="{metadata[urls][github][issues][new][docs_bug_content]}">documentation</a>,
              or for requesting new features and enhancements, please select the appropriate form from the
              <a href="{metadata[urls][github][issues][template_chooser]}">template chooser</a>.
            </p>
          </li>
        </ul>
        <blockquote>
          💡 <a href="{}"><b>Contact us</b></a>
          <br>
          <p align="justify">
            Can't find the right form or unsure about which one to choose?
            Ask a question in the
            <a href="{}">discussion forum</a>,
            or
            <a href="{metadata[urls][github][issues][new][discussion]}">contact us directly</a>.
          </p>
        </blockquote>
        <h3>⚠️ Verifying the bug</h3>

        Before submitting a report, please verify that:

        1. The issue you are experiencing is in fact a bug,
        and not a documented expected behavior.

        2. The bug is reproducible in the latest version of the software,
        and has not yet been reported.

        <blockquote>
            💡 <a href="{}"><b>Open a discussion instead!</b></a>
            <br>
            This verification process is non-trivial, and can be time-consuming.
            If you are not a collaborator and don't have the time to go through the process,
            you can always open a discussion instead; we will investigate the problem as soon as possible,
            and convert the discussion into an issue if the bug is verified.
        </blockquote>
        <h3>🤝 Code of conduct</h3>
        <p align="justify">
          Please make sure that you are following our
          <a href="{metadata[urls][github][code_of_conduct]}">Code of Conduct</a>,
          so that we can process the issue as soon as possible.
        </p>
        <h3>✅ Agreements</h3>

  - type: checkboxes
    id: terms
    attributes:
      label: >-
        To submit an API bug report, please agree to the following terms and conditions:
#      description: >-
#        Please make sure that you are following our
#        [Bug Report Guidelines](https://github.com/Armin-Ariamajd/TemplateRepo/blob/main/docs/CONTRIBUTING.md#how-to-contribute-changes),
#        so that we can process the issue as soon as possible.

      options:

        - label: >-
            I have read the [Contributing Guidelines]() and am following the [Bug Report Guidelines]().
          required: true

        - label: >-
            I have read, understood, and agree to follow the [Code of Conduct](https://github.com/Armin-Ariamajd/TemplateRepo/blob/main/docs/CODE_OF_CONDUCT.md).
          required: true

  - type: markdown
    attributes:
      value: |
        <br>
        <h2>System and Version Specifications</h2>

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: |
        Which operating systems have you tested?
        Please select all versions where you have encountered the bug.
      multiple: true
      options:
        - Linux
        - MacOS
        - Windows
    validations:
      required: true

  - type: dropdown
    id: python_version
    attributes:
      label: Python Version
      description: |
        Which Python versions have you tested?
        Please select all versions where you have encountered the bug.
      multiple: true
      options:
        - 3.11
        - 3.10
        - 3.9
    validations:
      required: true

  - type: dropdown
    id: package_version
    attributes:
      label: Package Version
      description: |
        Which versions of our software are affected?
        Please select all versions where you have encountered the bug.
      multiple: true
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        <br>
        <h2>Bug Report</h2>

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        <h3>🐍 Python API</h3>
        <p align="justify">
        If you have encountered the bug while using the Python API,
        </p>

  - type: input
    attributes:
      label: Fully Qualified Name
      description: |
        Please provide the fully qualified name of the API endpoint that is causing the problem.
      placeholder: "{}"
    validations:
      required: false

  - type: textarea
    id: code
    attributes:
      label: Minimal Reproducible Example (MRE)
      description: >-
        Please provide a minimal complete verifiable code example to reproduce the bug.

        ⚠️ The contents of this textfield will be automatically rendered as Python code,
        without the need to wrap it
      placeholder: "import {metadata[package][name]}"
      value: |
        import {metadata[package][name]}

      render: python
    validations:
      required: true


  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell


  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false

  - type: checkboxes
    attributes:
      label: Become a Collaborator
      description: >-
        Thank you again for filling this bug report.
      options:
        - label: >-
            I am willing to work on the issue and submit a bug fix.
          required: false
