# Template for bug reports
# Ref: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms


name: '📚 Docs  🪲 Bug Report  🌐 Website'
description: >-
  Report a technical problem in the documentation website,
  including broken page formatting, loading issues, and unexpected behavior.
labels: ["bug", "triage"]

body:

  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report!

  - type: dropdown
    id: package_version
    attributes:
      label: Package Version
      description: |
        Which versions of our software are affected?
        Please select all versions where you have encountered the bug.
      multiple: true
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
    validations:
      required: true

  - type: dropdown
    id: python_version
    attributes:
      label: |
        Which Python versions have you tested?
        Please select all versions where you have encountered the bug.
      multiple: true
      options:
        - 3.11
        - 3.10
        - 3.9

  - type: dropdown
    id: os
    attributes:
      label: |
        Which operating systems have you tested?
        Please select all versions where you have encountered the bug.
      multiple: true
      options:
        - Linux
        - MacOS
        - Windows

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true

  - type: textarea
    id: code
    attributes:
      label: Example
      description: Please provide the most minimal possible example to reproduce the bug.
      placeholder: "import pypackit"
      value: "import pypackit"
      render: python
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
