# Build the documentation with Sphinx and upload the builds as artifacts.

name: 'Docs: Build'
run-name: 'Docs: build from ${{github.ref}}'

on:
  workflow_dispatch:


jobs:

  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - uses: repodynamics/sphinxdocs@main
