

name: 'Package: Publish'
run-name: 'Package: Build from ${{github.ref}}'


on:
  workflow_call:
    inputs:
      platform:
        type: string
        default: 'TestPyPI'
        required: false
        description: |
          Platform to publish to; either 'TestPyPI' (default) or 'PyPI'.


jobs:
  package-release-pypi:
    name: Publish on ${{ inputs.platform }}
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.platform }}
      url: ${{ steps.script.outputs.download-url }}
    permissions:
      id-token: write
    steps:
      - name: 'Download sdist and wheels artifacts'
        uses: actions/download-artifact@v3
        with:
          name: Distribution Package
          path: dist

#      - name: 'Checkout script'
#        uses: actions/checkout@v3
#        with:
#          ref: ${{ github.base_ref }}
#          sparse-checkout: .github/script/workflow.py
#          sparse-checkout-cone-mode: false

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - shell: bash
        run: |
          # Install RepoDynamics
          echo "::group::Install Dependencies"
          python -m pip install repodynamics
          echo "::endgroup::"
          echo "::group::Display pip environment"
          python -m pip list
          echo "::endgroup::"

      - name: 'Run script'
        id: script
        env:
          RD_PYBUILD__PLATFORM: ${{ inputs.platform }}
          RD_PYBUILD__PATH_DIST: dist
        run: python -m repodynamics.actions pybuild publish

      - name: 'Upload package'
        uses: pypa/gh-action-pypi-publish@release/v1
        # https://github.com/marketplace/actions/pypi-publish
        with:
          packages-dir: dist
          repository-url: ${{ steps.script.outputs.upload-url }}
          verify-metadata: true
          verbose: true
          print-hash: true
          skip-existing: false
